#ifndef MONAR_CONFIG_H
#define MONAR_CONFIG_H

#define MN_CFG_DEVICE_REGISTRY_MAX 16u

#define MN_CFG_RUNTIME_BAREMETAL 1
#define MN_CFG_RUNTIME_POSIX 0
#define MN_CFG_RUNTIME_FREERTOS 0
#define MN_CFG_RUNTIME_RTTHREAD 0
#define MN_CFG_RUNTIME_ZEPHYR 0

#endif /* MONAR_CONFIG_H */
