#ifndef MONAR_BSP_BOARDS_ST_NUCLEO_F407ZG_BOARD_CONFIG_H
#define MONAR_BSP_BOARDS_ST_NUCLEO_F407ZG_BOARD_CONFIG_H

#define MN_BOARD_NAME "nucleo_f407zg"
#define MN_BOARD_CPU "cortex-m4"
#define MN_BOARD_VENDOR "st"

#endif /* MONAR_BSP_BOARDS_ST_NUCLEO_F407ZG_BOARD_CONFIG_H */
